services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: "django_appci"
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./AppCI:/AppCI
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
