services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_appci"
    expose:
      - "8000"
    volumes:
      - ./AppCI:/AppCI
    command: gunicorn AppCI.wsgi:application --bind 0.0.0.0:8000            
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
      - PG_HOST=db
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: "postgres_appci"
    ports:
      - "5435:5432"
    restart: unless-stopped
    env_file:
      -  ".env.prod"
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
  nginx-proxy:
    # image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    volumes:
      - ./AppCI:/AppCI
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/vhost.d/appci.rhonidev.com:/etc/nginx/vhost.d/appci.rhonidev.com:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app_network
  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
volumes:
  postgres_data:
  certs:
  html:
  vhost:
  acme:

networks:
  app_network:
    driver: bridge
