services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "django_appci"
    ports:
      - "5000:8000"
    volumes:
      - ./AppCI:/AppCI
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
      - PG_HOST=db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: "postgres_appci"
    ports:
      - "5435:5432"
    restart: unless-stopped
    env_file:
      -  ".env.prod"
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
